### ISSUE TITLE
Meson 1.3.0 only accepts numeric versions as `soversion` on macOS

### ISSUE THREAD

**Issue by matyalatte** [libui-ng/libui-ng#258]
You can't build libui-ng with meson 1.3.0 on macOS, becuase it uses `soversion` for `-compatibility_version` and `-current_version`. (Idk if it's a bug or not tho.)

```
cc  -o ***.A.dylib ***.o ... -compatibility_version A -current_version A ...

ld: malformed 32-bit x.y.z version number: A
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

To fix the error, we should use a numeric verison like `0`, or remove `soversion` and `darwin_versions` from library() options.

**Comment by szanni** [comment]
I believe this might still be an upstream issue as you suspected here [https://github.com/mesonbuild/meson/issues/12604](https://github.com/mesonbuild/meson/issues/12604).

According to the [docs](https://mesonbuild.com/Reference-manual_functions.html#library) `soversion` can be a string or an integer:
> [soversion](https://mesonbuild.com/Reference-manual_functions.html#library_soversion)                    : [str](https://mesonbuild.com/Reference-manual_elementary_str.html) | [int](https://mesonbuild.com/Reference-manual_elementary_int.html)                                                               # A string or integer specifying the soversion of this shared library,

We can probably use `0` here though or remove the code entirely as we are not releasing any versioned builds yet anyways.

**Comment by matyalatte** [comment]
> I believe this might still be an upstream issue

Idk if it should be fixed or not, but I reopened the issue.

> We do need to fix this ASAP though

Yeah, but cody seems busy lately...

**Comment by szanni** [comment]
> > I believe this might still be an upstream issue
> 
> Idk if it should be fixed or not, but I reopened the issue.

Thanks.

> > We do need to fix this ASAP though
> 
> Yeah, but cody seems busy lately...

Issues like this still get merged pretty promptly once there is a clear solution. It's bigger code reviews and feature PRs that typically get put on hold.

**Comment by szanni** [comment]
> To fix the error, we should use a numeric verison like `0`, or remove `soversion` and `darwin_versions` from library() options.

I believe completely removing `soversion` is probably the way to go for now.
On Linux systems at least the unversioned shared libs are usually symlinked to the latest versioned lib anyways.
Once we have proper versioning for libui-ng, we can do proper soversioning as well.

Only minor inconvenience I see here is all binding authors needing to update the so path.
